name: Test Action

on:
  push:

  workflow_dispatch:
    inputs:
      flagTest:
        description: 'Run integration tests pipeline in Staging before deploy to production'
        required: false
        type: boolean
        default: true

env:
  MUST_TEST: ${{ fromJSON('["true", "false"]')[github.event.inputs.flagTest == 'false'] }}

jobs:
  aah:
    runs-on: ubuntu-latest
    if: ${{ false }}
    steps:
      - name:  Just echo error
        run: echo 'echoing nothing but success' && exit 1
  foo:
    runs-on: ubuntu-latest
    # environment:
    #   name: production

    steps:
      - name: Print flagTest
        run: |
          if [ ${{ github.event.inputs.flagTest == false }} || ${{ job.status == 'success' }} ]; then
            SKIPPED_MESSAGE=${{ github.event.sender.login }} also skipped the tests. :thisisfine:
          fi

          echo "${SKIPPED_MESSAGE} echoed!"
          echo ${{ jobs.aah.status }}
