name: Test Action

on:
  push:

  workflow_dispatch:
    inputs:
      flagTest:
        description: 'Run integration tests pipeline in Staging before deploy to production'
        required: false
        type: boolean
        default: true
env:
  MUST_TEST: ${{ github.event.inputs.flagTest == true && true || false }}
jobs:
  foo:
    runs-on: ubuntu-latest
    if: ${{ env.MUST_TEST }}
    steps:
      - name: Print flagTest
        run: |
          echo '${{ github.event.inputs.flagTest }} echoed!'
