name: Test Action

on:
  push:

  workflow_dispatch:
    inputs:
      flagTest:
        description: 'Run integration tests pipeline in Staging before deploy to production'
        required: false
        type: boolean
        default: true

env:
  MUST_TEST: ${{ fromJSON('["true", "false"]')[github.event.inputs.flagTest == 'false'] }}

jobs:
  foo:
    runs-on: ubuntu-latest
    env:
      MUST_TEST: ${{ fromJSON('["true", "false"]')[github.event.inputs.flagTest == 'false'] }}
    if: env.MUST_TEST
    steps:
      - name: Print flagTest
        run: |
          echo '${{ env.MUST_TEST }} env echoed!'
          echo '${{ github.event.inputs.flagTest }} flag echoed!'
